In [5]:
import context
import numpy as np

In [33]:
a1 = context.Context(3, 10, 10)
print(a1.dims)

[1 0 9 8 3 6 4 5 7 2]
[6 1 7 5 9 2 0 4 3 8]
[4 0 5 2 7 6 8 3 1 9]
[[4 1 2 5 9 7 8 6 3 0]
 [7 0 8 4 1 3 9 2 5 6]
 [8 5 6 3 7 1 2 9 0 4]]


In [34]:
dimension = np.random.choice(10, size = 10, replace = False)
dimension

array([7, 6, 1, 4, 3, 8, 9, 2, 0, 5])

In [35]:
idx = 1 # idx ranges from 0 to 2, thus min_idx is 0, 2 or 4
min_idx = idx * 2 

In [36]:
# first occurence of min properties is returned
where_min = np.argmin(dimension)
where_min

8

In [37]:
# dim[[7, 2]] = dim[[2, 7]]
dimension[[where_min, min_idx]] = dimension[[min_idx, where_min]]

In [38]:
dimension[[where_min, min_idx]] # 8, 2

array([1, 0])

In [39]:
dimension

array([7, 6, 0, 4, 3, 8, 9, 2, 1, 5])

In [43]:
dimension[[1,1,1]]

array([6, 6, 6])

In [52]:
a1.view(dims = 2, dim_first = False, at_dim_idx = True)
a1.dims

AxisError: axis 1 is out of bounds for array of dimension 1

In [61]:
flatten_a1 = a1.view()
print(flatten_a1)

[4 7 8 1 0 5 2 8 6 5 4 3 9 1 7 7 3 1 8 9 2 6 2 9 3 5 0 0 6 4]
